CREATE TABLE User(
	USERNAME  VARCHAR(255)  PRIMARY KEY
);



CREATE TABLE karaokeFile(
	SONGID	 INT           PRIMARY KEY,
	USERNAME VARCHAR(255)  NOT NULL,

FOREIGN KEY(USERNAME) REFERENCES USER(USERNAME)
);



CREATE TABLE SONG(
	TITLE VARCHAR(55) PRIMARY KEY,
	ARTISTNAME VARCHAR(55) PRIMARY KEY,
	AUTHOR	VARCHAR(55),
	SINGER	VARCHAR(55),
	GUITARIST VARCHAR(55),
	DRUMMER	  VARCHAR(55),
	SONGID	  INT	NOT NULL,
	PREQUESTID INT,
	FREQUESTID INT,

FOREIGN KEY(SONGID) REFERENCES KARAOKEFILE(SONGID),
FOREIGN KEY(PREQUESTID) REFERENCES PRIMARYQUEUE(PREQUESTID),
FOREIGN KEY(FREQUESTID) REFERENCES FREEQUEUE(FREQUESTID)
); 



CREATE TABLE PRIMARYQUEUE(
	PREQUESTID  INT           PRIMARY KEY,
	TITLE	    VARCHAR(255)  NOT NULL,
	ARTISTNAME  VARCHAR(255)  NOT NULL,

FOREIGN KEY(TITLE) REFERENCES SONG(TITLE),
FOREIGN KEY(ARTISTNAME) REFERENCES SONG(ARTISTNAME)
);



CREATE TABLE FREEQUEUE(
	FREQUESTID  INT          PRIMARY KEY,
	TITLE       VARCHAR(255) NOT NULL,
	ARTISTNAME  VARCHAR(255) NOT NULL,

FOREIGN KEY(TITLE) REFERENCES SONG(TITLE),
FOREIGN KEY(ARTISTNAME) REFERENCES SONG(ARTISTNAME)
);



CREATE TABLE DJ(
	PREQUESTID  INT  NOT NULL,
	FREQUESTID  INT  NOT NULL,

FOREIGN KEY(PREQUESTID) REFERENCES PRIMARYQUEUE(PREQUESTID),
FOREIGN KEY(FREQUESTID) REFERENCES FREEQUEUE(FREQUESTID)
);